### ISSUE TITLE
Crash when passing in null to setPinnedDrawable()/setUnpinnedDrawable().

### ISSUE THREAD

**Issue by JimVanG** [f2prateek/progressbutton#39]
Fatal exception when passing in `null` to `setPinnedDrawable()` or `setUnpinnedDrawable()`. These methods should be able to handle passing in `null`, just as other Android widgets (`ImageView`, `ImageButton`, etc) handle passing in `null`.

**Comment by f2prateek** [comment]
Not really since the point of this widget is to show the 2 states. If you pass in null it won't be able to show that state to the user properly.
